# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: acc8e4c382444916d2b45905e280982dcdfbba75f4d1d8dd9007806af921efed37c9507c8b0b259cacecb70c04e02f12beb8b6c3f32c4ae56a31a0ceddd38193

test:
  secret_key_base: 12787eed2b4882a5aebc9b8f2f663a3e24566b31c9769ac48abfa122e272acf6ed3dd786bfe0143145389571a149531647d166a14121e5badc39a630e52cfc16

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
